#!/usr/bin/env bash

touch /tmp/got_in.txt
touch /home/codespace/got_in.txt

gem install homesick

homesick clone benjaminoakes/homesick-vi-everywhere
homesick symlink homesick-vi-everywhere --force
homesick clone ContinuityControl/dotfiles
homesick symlink dotfiles --force
