#!/usr/bin/env bash

if [ "$EUID" -ne 0 ]; then
  sudo="sudo"
else
  sudo=""
fi

$sudo apt-get update
$sudo apt-get install -y \
  ctop \
  curl \
  git \
  gron \
  jq \
  less \
  man-db \
  openssh-client \
  rlwrap \
  ruby \
  tmux \
  tree \
  unar \
  vim \
  wget \
  zsh
$sudo gem install --no-document homesick

curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

homesick clone benjaminoakes/homesick-vi-everywhere
homesick symlink homesick-vi-everywhere --force
homesick clone TigerDenHackers/dotfiles
homesick symlink dotfiles --force

mkdir -p ~/.zsh; echo '' > ~/.zsh/local.zsh
mkdir -p ~/.gitconfig.d; printf "\n" > ~/.gitconfig.d/user
# Might later include my own tmux config but for now, stop its complaining
mkdir -p ~/.tmux; echo '' > ~/.tmux/user.conf
